---
abstract: 'build and install librdkafka'
author:
  - unknown
build_requires: {}
configure_requires:
  Alien::Base::ModuleBuild: '0.005'
  Module::Build: '0.28'
dynamic_config: 1
generated_by: 'Module::Build version 0.4218, CPAN::Meta::Converter version 2.150005'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-Librdkafka
requires:
  Alien::Base: '0.005'
  File::ShareDir: '1.00'
version: v0.9.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
